config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => "mailbox#inbox", as: :mailbox_inbox

  get 'mailbox/sent' => "mailbox#sent", as: :mailbox_sent

  get 'mailbox/trash' => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  root "static_pages#home"

  resources(:users, only:[:show])

  resources(:arenas, only: [:index, :show]) do
    resources(:games, only: [:create, :show])
  end

  resources(:games, only: [:show, :index]) do
    resources(:invites, only: [:create])
  end

  get "invites/:id/accept" => "invites#accept"
  get "invites/:id/reject" => "invites#reject"
  get "invites/:id" => "invites#show"

  get "games/:game_id/requests/:id" => "requests#please"
  get "games/:game_id/invites/:id/accept" => "invites#send_invite"
  get "games/:game_id/invites/:id/reject" => "invites#reject_invite"

  get "/games/:id/cancel" => "invites#cancel"

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    @receipts = @receipts.reverse
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="col s12 mail-sub">
  <div class="col s9">
      <div class="chip">
      	<% if conversation.originator.image.url %>
	      	<img src="<%= conversation.originator.image.url %>">
	    <% else %>
	    	<img src="http://cdn4.sportngin.com/attachments/text_block/1798/9513/soccer-ball_small.jpg">
	    <% end %>
		<%= conversation.originator.username %>
      </div>
      <span> at <%= conversation.messages.last.created_at.strftime("%b %d, %I:%M%p") %></span>
  </div>

  <div class="col s2">
      <%= link_to "View", conversation_path(conversation), :class => "waves-effect waves-light btn" %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations do |f| %>
    <div class="field">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.where.not(id: current_user).collect {|p| [ p.username, p.id ] }, {}, { multiple: true , style: "display: inline-block;", class: "chosen-select input-field" })%>
    </div>
    <div class="field">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "input-field" %>
    </div>
    <div class="field">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'input-field',placeholder: "Type your message here", rows: 4  %>
    </div>
    <br>
    <%= f.submit "Send Message", class: "waves-effect waves-light btn" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="col s12 mail-sub">
      <div class="col s9">
          <span>
          <% if message.sender == current_user %>
            <div class="chip">
              <% if message.sender.image.url %>
                <img src="<%= message.sender.image.url %>">
              <% else %>
                <img src="http://cdn4.sportngin.com/attachments/text_block/1798/9513/soccer-ball_small.jpg">
              <% end %>
              <span class="red-text"><%= message.sender.username %></span>
            </div>
          <% else %>
            <div class="chip">
              <% if message.sender.image.url %>
                <img src="<%= message.sender.image.url %>">
              <% else %>
                <img src="http://cdn4.sportngin.com/attachments/text_block/1798/9513/soccer-ball_small.jpg">
              <% end %>
              <span class="blue-text"><%= message.sender.username %></span>
            </div>
          <% end %>
          </span>

          <span> at <%= message.created_at.strftime("%b %d, %I:%M%p") %>: </span>
          <span class="blue-grey-text darken-3"><%= message.body %></span>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render "devise/shared/nav" %>

<div class="row">
	<div class="col s3 inbox-left" style="padding-bottom: 130px;">
		<ul>
			<li>
				<a href="/conversations/new">
					<i class="material-icons">textsms</i>
					Compose
				</a>
			</li>
			<li>
				<a href="/mailbox/inbox">
					<i class="material-icons">email</i>
					Inbox
					<span class="new badge" style="position: static;"><%= unread_messages_count %></span>
				</a>
			</li>
			<li>
				<a href="/mailbox/sent">
					<i class="material-icons">send</i>
					Sent
				</a>
			</li>
			<li>
				<a href="/mailbox/trash">
					<i class="material-icons">delete</i>
					Trash
				</a>
			</li>
		</ul>

	</div>

	<div class="col s6">
		<h4>New Message:</h4>
		<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>
	</div>
</div>

app/views/conversations/show.html.erb
<%= render "devise/shared/nav" %>

<div class="row">
  <div class="col s3 inbox-left" style="padding-bottom: 130px;">
    <ul>
      <li>
        <a href="/conversations/new">
          <i class="material-icons">textsms</i>
          Compose
        </a>
      </li>
      <li>
        <a href="/mailbox/inbox">
          <i class="material-icons">email</i>
          Inbox
          <span class="new badge" style="position: static;"><%= unread_messages_count %></span>
        </a>
      </li>
      <li>
        <a href="/mailbox/sent">
          <i class="material-icons">send</i>
          Sent
        </a>
      </li>
      <li>
        <a href="/mailbox/trash">
          <i class="material-icons">delete</i>
          Trash
        </a>
      </li>
    </ul>
  </div>

  <div class="col s9" style="padding-top: 40px">

    <div class="col s8">
      <div>
        <div class="message-list">
          <%= render partial: 'messages' %>
        </div>

        <div class="reply-box">
          <!-- Reply Form -->
          <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
                <%= f.text_area :body, placeholder: "Reply Message", rows: 4 %>
                <%= f.submit "Reply", class: 'waves-effect waves-light btn left light-blue lighten-1' %>
          <% end %>
          <% if conversation.is_trashed?(current_user) %>
              <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'waves-effect waves-light btn right', method: :post %>
          <% else %>
              <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'waves-effect waves-light btn red right', method: :post,
                          data: {confirm: 'Are you sure?'} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>




</div>