config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => "mailbox#inbox", as: :mailbox_inbox

  get 'mailbox/sent' => "mailbox#sent", as: :mailbox_sent

  get 'mailbox/trash' => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  root "static_pages#home"

  resources(:users, only:[:show])

  resources(:arenas, only: [:index, :show]) do
    resources(:games, only: [:create, :show])
  end

  resources(:games, only: [:show, :index]) do
    resources(:invites, only: [:create])
  end

  get "invites/:id/accept" => "invites#accept"
  get "invites/:id/reject" => "invites#reject"
  get "invites/:id" => "invites#show"

  get "games/:game_id/requests/:id" => "requests#please"
  get "games/:game_id/invites/:id/accept" => "invites#send_invite"
  get "games/:game_id/invites/:id/reject" => "invites#reject_invite"

  get "/games/:id/cancel" => "invites#cancel"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  has_many :invites
  has_many :requests

  validates :username, :email, presence: true
  validates :username, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         mount_uploader :image, UserImageUploader

  acts_as_messageable

  def mailboxer_name
  	self.name
  end

  def mailboxer_email(object)
  	self.email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [ "show" ]
	def show
		@user = User.find_by(id: params[:id])
		@past_games = @user.games.where('start_time < ?', Time.zone.now)
		@upcoming_games = @user.games.where('start_time > ?', Time.zone.now)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "devise/shared/nav" %>

<div class="container">
	<div class="row" style="margin-top: 25px;">
		<div class="col s4">
			<div class="center-align pro-pic">
				<% if @user.image.url %>
					<img class="pro-pic responsive-img circle" style="height: 150px; width=150px;" src="<%= @user.image.url %>">
				<% else %>
					<img class="pro-pic responsive-img circle" style="height: 150px; width=150px;" src="http://png.clipart.me/graphics/thumbs/190/soccer-modern-flat-icon_190755464.jpg"/>
				<% end %>
			</div>
		</div>

		<div class="col s8">
			<div class="info-div">
				<span class="username-div"><%= @user.username %></span>

				<% if @user.id == current_user.id %>
					<%= link_to "Edit Profile", edit_user_registration_path, :class => "waves-effect waves-light btn profile-btn" %>
				<% else %>
					<%= link_to "Message User", new_conversation_path, :class => "waves-effect waves-light btn profile-btn" %>
				<% end %>
			</div>

			<div>
			</div>
		</div>
	</div>

	<div class="row" style="background: #fff">
		<section id="player-games">
			<div class="col s12 m6 offset-m3">
				<ul class="tabs" style="width: 100%;">
					<li class="tab col s6" style="width: 50%;">
						<a href="#past-games" class="active js-past green-text text-darken-2">Past Games</a>
					</li>
					<li class="tab col s6" style="width:50%;">
						<a href="#upcoming-games" class="js-upcoming green-text text-darken-2">Upcoming Games</a>
					</li>
					<div class="indicator" style="right: 299px; left: 0px;"></div>
					<div class="indicator" style="right: 299px; left: 0px;"></div>
				</ul>
			</div>

			<div class="col s12" id="past-games">
				<div>
			        <ul class="center-align">
			          <% @past_games.each do |game| %>
				          	<li class="col s4">
				            	<div class="card arena-card">
				              		<div class="card-image waves-effect waves-block waves-light">
				                		<img class="activator card-img" src="<%= game.arena.image.url if game.arena.image %>">
				              		</div>

					              	<div class="card-content">
				                		<div class="card-title activator grey-text text-darken-4">
				                  			<h6 class="center-align" style="font-weight: 700;"><%= game.arena.name %></h6>
				                  			<h6 class="center-align">
				                    			Organizer:
				                    			<a href="/users/<%= game.user.id %>">
				                      				<%= game.user.username %>
				                    			</a>
				                  			</h6>
				                  			<h6 class="center-align"><%= (game.start_time).strftime("%A %b %d at %I:%M %p") %> to <%= (game.end_time).strftime("%I:%M %p") %></h6>
				           	  			</div>
				            		</div>
				            	</div>
				          	</li>
			          <% end %>
			        </ul>
      			</div>
			</div>

			<div class="col s12" id="upcoming-games">
				<div>
			        <ul class="center-align">
			          	<% @upcoming_games.each do |game| %>
					          	<li class="col s4" style="list-style-type: none;">
					            	<div class="card arena-card">
					              		<div class="card-image waves-effect waves-block waves-light">
					                		<img class="activator card-img" src="<%= game.arena.image.url if game.arena.image %>">
					              		</div>

						              	<div class="card-content">
					                		<div class="card-title activator grey-text text-darken-4">
					                  			<h6 class="center-align" style="font-weight: 700;">
					                  				<a href="/games/<%= game.id %>">
					                  					<%= game.arena.name %>
					                  				</a>
					                  			</h6>
					                  			<h6 class="center-align">
					                    			Organizer:
					                    			<a href="/users/<%= game.user.id %>">
					                      				<%= game.user.username %>
					                    			</a>
					                  			</h6>
					                  			<h6 class="center-align"><%= (game.start_time).strftime("%A %b %d at %I:%M %p") %> to <%= (game.end_time).strftime("%I:%M %p") %></h6>
					           	  			</div>
					            		</div>
					            	</div>
					          	</li>
			        	<% end %>
			        </ul>
      			</div>
			</div>
		</section>
	</div>
</div>