config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => "mailbox#inbox", as: :mailbox_inbox

  get 'mailbox/sent' => "mailbox#sent", as: :mailbox_sent

  get 'mailbox/trash' => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  root "static_pages#home"

  resources(:users, only:[:show])

  resources(:arenas, only: [:index, :show]) do
    resources(:games, only: [:create, :show])
  end

  resources(:games, only: [:show, :index]) do
    resources(:invites, only: [:create])
  end

  get "invites/:id/accept" => "invites#accept"
  get "invites/:id/reject" => "invites#reject"
  get "invites/:id" => "invites#show"

  get "games/:game_id/requests/:id" => "requests#please"
  get "games/:game_id/invites/:id/accept" => "invites#send_invite"
  get "games/:game_id/invites/:id/reject" => "invites#reject_invite"

  get "/games/:id/cancel" => "invites#cancel"

end

app/models/arena.rb
class Arena < ActiveRecord::Base
	has_many :games

	mount_uploader :image, ArenaImageUploader
end

app/controllers/arenas_controller.rb
class ArenasController < ApplicationController
	before_action :authenticate_user!, only: [ "show" ]
	def index
		@arenas = Arena.all
	end

	def show
		@arena = Arena.find_by(id: params[:id])
		@game = @arena.games.new
	end
end

app/helpers/arenas_helper.rb
module ArenasHelper
end

app/views/arenas/index.html.erb
<%= render "devise/shared/nav" %>

<div class="container">
  <div class="row">
    <div class="col s12">

      <h4 class="center-align">Pick An Arena</h4>

      <div>
        <ul class="center-align">
          <% @arenas.each do |arena| %>
          <li class="col s4">
            <div class="card arena-card">
              <div class="card-image waves-effect waves-block waves-light">
                <img class="activator card-img" src="<%= arena.image.url if arena.image %>">
              </div>

              <div class="card-content">
                <div class="card-title activator grey-text text-darken-4">
                  <h5 class="center-align"><%= arena.name %></h5>
                </div>

                <div class="center-align"><a class="card-btn waves-effect waves-light btn" href="/arenas/<%= arena.id %>">Book This Arena</a></div>
              </div>

              <div class="card-reveal">
                <div class="card-title grey-text text-darken-4">
                  <h5 class="center-align"><%= arena.name %><i class="material-icons right red-text">close</i></h5>
                </div>
                <a href="<%= arena.website %>">Website</a>
                <hr>
                <p>Address: <%= arena.address %></p>
                <p>Contact Number: <%= arena.number %></p>
                <p>Size: <%= arena.size %></p>
                <p>Price per hour: <%= arena.price %></p>
              </div>
            </div>
          </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/arenas/show.html.erb
<%= render "devise/shared/nav" %>

<div class="container arena-show-page">
	<div class="row">
		<div class="col s12">
			<h1 class="center-align">
				<%= @arena.name %>
			</h1>
		</div>
	</div>

		<!-- Confirming this should display the form with time slots -->
	<div class="row">
		<div class="col s12 arena-call">
			<h4>Call the arena to reserve your time slot</h4>
			<h5 class="red-text"><%= @arena.number %></h5>
			<button class="js-confirm-booking waves-effect waves-light btn", style="margin-bottom: 20px; margin-top: 10px;">I reserved my time slot</button>
		</div>
	</div>

		<!-- Reserving time slots opens up the invite friends form -->
	<div class="row js-reserve-time" style="display:none;">
		<div class="arena-form", style="padding: 25px;">
			<%= form_for [@arena, @game], url: arena_games_path(@arena) do |f|%>
				<div class="field">
					<%= label_tag :date %>
					<%= date_field_tag :date, nil, :class => "datepicker" %>
				</div>

				<div class="field">
					<%= f.label :start_time %>
					<%= f.time_field :start_time, :class => "timepicker" %>
				</div>

				<div class="field">
					<%= f.label :end_time %>
					<%= f.time_field :end_time, :class => "timepicker" %>
				</div>

				<div class="center-align">
					<%= f.submit "Reserve", :class => "waves-effect waves-light btn", :style => "margin-top: 10px; margin-bottom: 10px" %>
				</div>
			<% end %>
		</div>
	</div>
</div>